language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: python setup.py test
env:
  global:
    secure: fMnsP0vfFsbhcu8q9d3y0FLas3BLcH0Au6rh7d0RDDDbpgBb6JEmsSKOzA1kIEl3y1p7iEgsVQ5HrGITnMCFJckxp4w79+uqrQ8wSL44y0pRR/9G/ae+fzANxRsH68NNEDdNp1D11MkfRyxuw39mvfxPanvne/eexmRqomW2/vG2I0Z4E780zJZEOumNWYPdIlWAoIU1MeJ6bAHnSUBjiFMg5VtesBc2pIPYTwVkReov7wTWzq1VABaYfk0aFYhdEhQUDgq9oiPU+XasBxY5W+yPWbRfF9W6g45nTCQxLHwwF3nIutlwDI8CQ2Zu2pgwA17yQbBGjTS6agzYtW3vHF+YBjwS6a7JolFiR034Jvu7gMBeJSFjt7AlKNYFZSO1wE8BAoaE2+uW+qT7BCO4R9BIVfeBPVzbFrs9avGGMJ3kvbk8LyWufphOHGUBwWjXUkqEKtqCHypjA1zE7DhTfKFLKQ99NIN9tAYiqivXl1gLipPq3GTxfBOHXPZ5G+7upPV3t58umjPbQ9NNxZvZiCkTkN4ZQecKv6mMvKEDEjEsg/EvcErvV1izALjyyzX2XbMHJRBjEqqIAc12pacmeh2GrEcM1Eo6ayr0y8qsDPFI63uwonFvTfBTr3iHI7fbpGMwSljT1HbmzqeFzbGcco0dHen7+ttjeGYj/rH0qJI=
